const STATUS_CODE = {
    OK: 200,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 403,
    NOT_FOUND: 404,
    INTERNAL_ERROR: 500,
    USER_ALREADY_EXISTS: 409,
    MISSING_OR_INCORRECT_CREDIENTIALS:401
};


module.exports = {
    STATUS_CODE
}
